// Code generated from CandyOJ production bundle. DO NOT EDIT.

package api

// ParamHint 描述接口已知的请求字段（从前端调用点提取）
type ParamHint struct {
	Name string
	Hint string // 前端取值来源，仅作提示
}

// Endpoint 描述一个 CandyOJ 后端接口
type Endpoint struct {
	Path     string   // 接口路径，如 /Match/getMatchList
	Method   string   // GET 或 POST
	Style    string   // query | body | upload —— 决定参数放在哪里
	Resource string   // 资源名，如 match
	Action   string   // 动作名，如 get-match-list
	Aliases  []string // 短别名，如 list
	Summary  string
	Params   []ParamHint
}

// Style 常量
const (
	StyleQuery  = "query"  // 参数放 URL 查询串（本项目 $get / $post 的默认行为）
	StyleBody   = "body"   // 参数放 JSON 请求体（$post2）
	StyleUpload = "upload" // multipart/form-data（$upfile）
)

// Endpoints 全部 190 个接口
var Endpoints = []Endpoint{
	{
		Path:     "/Bag/addBagForMaster",
		Method:   "POST",
		Style:    "query",
		Resource: "bag",
		Action:   "add-bag-for-master",
		Aliases:  []string{"create"},
		Summary:  "Create",
		Params: []ParamHint{
			{Name: "F_MasterID", Hint: "this.settingMasterID"},
			{Name: "F_BagID", Hint: "e.join(\",\")"},
		},
	},
	{
		Path:     "/Bag/addBagType",
		Method:   "POST",
		Style:    "query",
		Resource: "bag",
		Action:   "add-bag-type",
		Aliases:  nil,
		Summary:  "Create",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "\"\""},
			{Name: "F_Name", Hint: "\"\""},
			{Name: "F_Sort", Hint: "\"\""},
			{Name: "F_CourseID", Hint: "[]"},
		},
	},
	{
		Path:     "/Bag/bagDel",
		Method:   "POST",
		Style:    "query",
		Resource: "bag",
		Action:   "bag-del",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "e"},
		},
	},
	{
		Path:     "/Bag/bagPartSave",
		Method:   "POST",
		Style:    "upload",
		Resource: "bag",
		Action:   "bag-part-save",
		Aliases:  nil,
		Summary:  "Save",
		Params:   nil,
	},
	{
		Path:     "/Bag/bagSave",
		Method:   "POST",
		Style:    "query",
		Resource: "bag",
		Action:   "bag-save",
		Aliases:  nil,
		Summary:  "Save",
		Params:   nil,
	},
	{
		Path:     "/Bag/bagStatus",
		Method:   "POST",
		Style:    "query",
		Resource: "bag",
		Action:   "bag-status",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params:   nil,
	},
	{
		Path:     "/Bag/delBagType",
		Method:   "POST",
		Style:    "query",
		Resource: "bag",
		Action:   "del-bag-type",
		Aliases:  []string{"delete"},
		Summary:  "Delete",
		Params:   nil,
	},
	{
		Path:     "/Bag/getBagDetail",
		Method:   "POST",
		Style:    "query",
		Resource: "bag",
		Action:   "get-bag-detail",
		Aliases:  []string{"view"},
		Summary:  "Show details",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/Bag/getBagList",
		Method:   "POST",
		Style:    "query",
		Resource: "bag",
		Action:   "get-bag-list",
		Aliases:  []string{"list"},
		Summary:  "List (paginated: data.list + data.count)",
		Params: []ParamHint{
			{Name: "F_Name", Hint: "\"\""},
			{Name: "time", Hint: "\"\""},
			{Name: "F_StartTime", Hint: "\"\""},
			{Name: "F_EndTime", Hint: "\"\""},
			{Name: "page", Hint: "1"},
			{Name: "F_Type", Hint: "\"\""},
		},
	},
	{
		Path:     "/Bag/getBagTypeList",
		Method:   "POST",
		Style:    "query",
		Resource: "bag",
		Action:   "get-bag-type-list",
		Aliases:  nil,
		Summary:  "List (paginated: data.list + data.count)",
		Params: []ParamHint{
			{Name: "F_CourseID", Hint: "this.F_CourseID"},
			{Name: "F_ChapterID", Hint: "this.F_ChapterID"},
		},
	},
	{
		Path:     "/Bag/getBagTypeListForManager",
		Method:   "POST",
		Style:    "query",
		Resource: "bag",
		Action:   "get-bag-type-list-for-manager",
		Aliases:  nil,
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/Bag/getClassMatchList",
		Method:   "POST",
		Style:    "query",
		Resource: "bag",
		Action:   "get-class-match-list",
		Aliases:  nil,
		Summary:  "List (paginated: data.list + data.count)",
		Params: []ParamHint{
			{Name: "F_BagID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/Bag/getMasterBag",
		Method:   "POST",
		Style:    "query",
		Resource: "bag",
		Action:   "get-master-bag",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_MasterID", Hint: "t.F_ID"},
		},
	},
	{
		Path:     "/Chapter/addExamToChapter",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter",
		Action:   "add-exam-to-chapter",
		Aliases:  []string{"create"},
		Summary:  "Create",
		Params: []ParamHint{
			{Name: "F_ChapterID", Hint: "s.$route.params.id"},
			{Name: "F_ExamID", Hint: "t.F_ID"},
			{Name: "F_Sort", Hint: "a"},
		},
	},
	{
		Path:     "/Chapter/chapterExamRank",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter",
		Action:   "chapter-exam-rank",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "this.$route.params.id"},
			{Name: "F_ClassID", Hint: "t"},
		},
	},
	{
		Path:     "/Chapter/chapterPartSave",
		Method:   "POST",
		Style:    "upload",
		Resource: "chapter",
		Action:   "chapter-part-save",
		Aliases:  nil,
		Summary:  "Save",
		Params:   nil,
	},
	{
		Path:     "/Chapter/chapterRank",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter",
		Action:   "chapter-rank",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "this.$route.params.id"},
			{Name: "F_ClassID", Hint: "t"},
		},
	},
	{
		Path:     "/Chapter/chapterSave",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter",
		Action:   "chapter-save",
		Aliases:  []string{"save"},
		Summary:  "Save",
		Params: []ParamHint{
			{Name: "F_Name", Hint: "\"\""},
			{Name: "F_Memo", Hint: "\"\""},
			{Name: "F_Order", Hint: "\"\""},
			{Name: "F_Status", Hint: "\"1\""},
			{Name: "F_CourseID", Hint: "this.$route.params.id"},
			{Name: "F_ID", Hint: "\"\""},
		},
	},
	{
		Path:     "/Chapter/delExamFromChapter",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter",
		Action:   "del-exam-from-chapter",
		Aliases:  []string{"delete"},
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "t.F_CsID"},
		},
	},
	{
		Path:     "/Chapter/deleteChapter",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter",
		Action:   "delete-chapter",
		Aliases:  nil,
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "t"},
		},
	},
	{
		Path:     "/Chapter/getChapterDetail",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter",
		Action:   "get-chapter-detail",
		Aliases:  []string{"view"},
		Summary:  "Show details",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/Chapter/getChapterList",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter",
		Action:   "get-chapter-list",
		Aliases:  []string{"list"},
		Summary:  "List (paginated: data.list + data.count)",
		Params: []ParamHint{
			{Name: "F_CourseID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/Chapter/uploadChapterFile",
		Method:   "POST",
		Style:    "upload",
		Resource: "chapter",
		Action:   "upload-chapter-file",
		Aliases:  nil,
		Summary:  "Upload file",
		Params: []ParamHint{
			{Name: "name", Hint: "\"v-rankingpre\""},
			{Name: "props", Hint: "[\"refreshTime\"]"},
			{Name: "data", Hint: "function() { return { selClass: [], selClassIDArr:"},
			{Name: "mounted", Hint: "function() { this.getCanMoveClassList() }"},
			{Name: "watch", Hint: "{ refreshTime: function() { this.chapterRank(this."},
			{Name: "methods", Hint: "{ getCodeContent: function(t) { var e = this; 0 !="},
		},
	},
	{
		Path:     "/ChapterSubject/addChapterSubjectType",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter-subject",
		Action:   "add-chapter-subject-type",
		Aliases:  []string{"create"},
		Summary:  "Create",
		Params:   nil,
	},
	{
		Path:     "/ChapterSubject/addSubjectToChapter",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter-subject",
		Action:   "add-subject-to-chapter",
		Aliases:  nil,
		Summary:  "Create",
		Params: []ParamHint{
			{Name: "F_ChapterID", Hint: "this.$chapterID"},
			{Name: "F_SubjectID", Hint: "this.resList.join(\",\")"},
		},
	},
	{
		Path:     "/ChapterSubject/addSubjectToChapterNew",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter-subject",
		Action:   "add-subject-to-chapter-new",
		Aliases:  nil,
		Summary:  "Create",
		Params: []ParamHint{
			{Name: "F_ChapterID", Hint: "i.$route.params.id"},
			{Name: "F_SubjectID", Hint: "t.F_ID"},
			{Name: "F_Sort", Hint: "r"},
			{Name: "F_Type", Hint: "t.F_Type"},
		},
	},
	{
		Path:     "/ChapterSubject/delChapterSubjectType",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter-subject",
		Action:   "del-chapter-subject-type",
		Aliases:  []string{"delete"},
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "t.F_ID"},
		},
	},
	{
		Path:     "/ChapterSubject/deletechaptersubject",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter-subject",
		Action:   "deletechaptersubject",
		Aliases:  nil,
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "t.F_CsID"},
		},
	},
	{
		Path:     "/ChapterSubject/getAllSubject",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter-subject",
		Action:   "get-all-subject",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params:   nil,
	},
	{
		Path:     "/ChapterSubject/getChapterSubjectListNew",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter-subject",
		Action:   "get-chapter-subject-list-new",
		Aliases:  []string{"list"},
		Summary:  "List (paginated: data.list + data.count)",
		Params: []ParamHint{
			{Name: "F_ChapterID", Hint: "this.$chapterID"},
		},
	},
	{
		Path:     "/ChapterSubject/getSubjectForAdd",
		Method:   "POST",
		Style:    "query",
		Resource: "chapter-subject",
		Action:   "get-subject-for-add",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_ChapterID", Hint: "t.F_ID"},
		},
	},
	{
		Path:     "/Course/addCourseForMaster",
		Method:   "POST",
		Style:    "query",
		Resource: "course",
		Action:   "add-course-for-master",
		Aliases:  []string{"create"},
		Summary:  "Create",
		Params: []ParamHint{
			{Name: "F_MasterID", Hint: "this.settingMasterID"},
			{Name: "F_CourseID", Hint: "e.join(\",\")"},
		},
	},
	{
		Path:     "/Course/courseExamRank",
		Method:   "POST",
		Style:    "query",
		Resource: "course",
		Action:   "course-exam-rank",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "this.$route.params.id"},
			{Name: "F_ClassID", Hint: "t"},
		},
	},
	{
		Path:     "/Course/courseRank",
		Method:   "POST",
		Style:    "query",
		Resource: "course",
		Action:   "course-rank",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "this.$route.params.id"},
			{Name: "F_ClassID", Hint: "t"},
		},
	},
	{
		Path:     "/Course/courseSave",
		Method:   "POST",
		Style:    "upload",
		Resource: "course",
		Action:   "course-save",
		Aliases:  []string{"save"},
		Summary:  "Save",
		Params:   nil,
	},
	{
		Path:     "/Course/deleteCourse",
		Method:   "POST",
		Style:    "query",
		Resource: "course",
		Action:   "delete-course",
		Aliases:  []string{"delete"},
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "t"},
		},
	},
	{
		Path:     "/Course/getCanAddCourse",
		Method:   "POST",
		Style:    "query",
		Resource: "course",
		Action:   "get-can-add-course",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_ClassID", Hint: "t.F_ID"},
		},
	},
	{
		Path:     "/Course/getCourseChapter",
		Method:   "POST",
		Style:    "query",
		Resource: "course",
		Action:   "get-course-chapter",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params:   nil,
	},
	{
		Path:     "/Course/getCourseList",
		Method:   "POST",
		Style:    "query",
		Resource: "course",
		Action:   "get-course-list",
		Aliases:  []string{"list"},
		Summary:  "List (paginated: data.list + data.count)",
		Params: []ParamHint{
			{Name: "page", Hint: "t"},
		},
	},
	{
		Path:     "/Course/getCourseStudent",
		Method:   "POST",
		Style:    "query",
		Resource: "course",
		Action:   "get-course-student",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "page", Hint: "t"},
		},
	},
	{
		Path:     "/Course/getMasterCourse",
		Method:   "POST",
		Style:    "query",
		Resource: "course",
		Action:   "get-master-course",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_MasterID", Hint: "t.F_ID"},
		},
	},
	{
		Path:     "/Course/getStudentClass",
		Method:   "POST",
		Style:    "query",
		Resource: "course",
		Action:   "get-student-class",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params:   nil,
	},
	{
		Path:     "/Course/setClassCourse",
		Method:   "POST",
		Style:    "query",
		Resource: "course",
		Action:   "set-class-course",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_CourseID", Hint: "e.join(\",\")"},
			{Name: "F_ClassID", Hint: "this.$F_ClassID"},
		},
	},
	{
		Path:     "/Difficulty/deleteDifficulty",
		Method:   "POST",
		Style:    "query",
		Resource: "difficulty",
		Action:   "delete-difficulty",
		Aliases:  []string{"delete"},
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "t.F_ID"},
		},
	},
	{
		Path:     "/Difficulty/getDifficultyList",
		Method:   "POST",
		Style:    "query",
		Resource: "difficulty",
		Action:   "get-difficulty-list",
		Aliases:  []string{"list"},
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/Difficulty/saveDifficulty",
		Method:   "POST",
		Style:    "query",
		Resource: "difficulty",
		Action:   "save-difficulty",
		Aliases:  []string{"save"},
		Summary:  "Save",
		Params: []ParamHint{
			{Name: "F_Name", Hint: "\"\""},
			{Name: "F_Sort", Hint: "\"\""},
			{Name: "F_ID", Hint: "\"\""},
		},
	},
	{
		Path:     "/Exam/addExamSubject",
		Method:   "POST",
		Style:    "upload",
		Resource: "exam",
		Action:   "add-exam-subject",
		Aliases:  []string{"create"},
		Summary:  "Create",
		Params: []ParamHint{
			{Name: "F_ExamID", Hint: "this.$route.query.examid"},
			{Name: "F_Score", Hint: "\"2\""},
			{Name: "F_Sort", Hint: "\"\""},
			{Name: "F_Title", Hint: "\"\""},
			{Name: "F_Type", Hint: "\"1\""},
			{Name: "F_Tips", Hint: "\"\""},
			{Name: "F_Coding", Hint: "\"\""},
			{Name: "F_A", Hint: "\"\""},
			{Name: "F_B", Hint: "\"\""},
			{Name: "F_C", Hint: "\"\""},
			{Name: "F_D", Hint: "\"\""},
			{Name: "F_AnswerChoice", Hint: "\"A\""},
			{Name: "F_Answer", Hint: "[{ answer: [], score: 0 }]"},
			{Name: "F_KongNum", Hint: "1"},
			{Name: "F_ID", Hint: "\"\""},
			{Name: "F_AImg", Hint: "\"\""},
			{Name: "F_BImg", Hint: "\"\""},
			{Name: "F_CImg", Hint: "\"\""},
			{Name: "F_DImg", Hint: "\"\""},
			{Name: "F_Img", Hint: "\"\""},
		},
	},
	{
		Path:     "/Exam/deleteExam",
		Method:   "POST",
		Style:    "query",
		Resource: "exam",
		Action:   "delete-exam",
		Aliases:  []string{"delete"},
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "e.list[t].F_ID"},
		},
	},
	{
		Path:     "/Exam/deleteExamSubject",
		Method:   "POST",
		Style:    "query",
		Resource: "exam",
		Action:   "delete-exam-subject",
		Aliases:  nil,
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "e.subject_list[t].F_ID"},
		},
	},
	{
		Path:     "/Exam/getExamList",
		Method:   "POST",
		Style:    "query",
		Resource: "exam",
		Action:   "get-exam-list",
		Aliases:  []string{"list"},
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/Exam/getExamListManager",
		Method:   "POST",
		Style:    "query",
		Resource: "exam",
		Action:   "get-exam-list-manager",
		Aliases:  nil,
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/Exam/getExamLog",
		Method:   "POST",
		Style:    "query",
		Resource: "exam",
		Action:   "get-exam-log",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_ExamID", Hint: "this.$route.query.examid"},
		},
	},
	{
		Path:     "/Exam/getExamLogListNew",
		Method:   "POST",
		Style:    "query",
		Resource: "exam",
		Action:   "get-exam-log-list-new",
		Aliases:  nil,
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/Exam/getExamLogSubject",
		Method:   "POST",
		Style:    "query",
		Resource: "exam",
		Action:   "get-exam-log-subject",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_ExamLogID", Hint: "e"},
		},
	},
	{
		Path:     "/Exam/getExamSubject",
		Method:   "POST",
		Style:    "query",
		Resource: "exam",
		Action:   "get-exam-subject",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_ExamID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/Exam/getStudentExamLogList",
		Method:   "POST",
		Style:    "query",
		Resource: "exam",
		Action:   "get-student-exam-log-list",
		Aliases:  nil,
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/Exam/saveExam",
		Method:   "POST",
		Style:    "query",
		Resource: "exam",
		Action:   "save-exam",
		Aliases:  []string{"save"},
		Summary:  "Save",
		Params: []ParamHint{
			{Name: "F_Name", Hint: "\"\""},
			{Name: "F_Sort", Hint: "\"\""},
			{Name: "F_Status", Hint: "\"1\""},
			{Name: "F_Des", Hint: "\"\""},
			{Name: "F_Time", Hint: "\"\""},
			{Name: "F_ID", Hint: "\"\""},
		},
	},
	{
		Path:     "/Exam/saveImg",
		Method:   "POST",
		Style:    "upload",
		Resource: "exam",
		Action:   "save-img",
		Aliases:  nil,
		Summary:  "Save",
		Params:   nil,
	},
	{
		Path:     "/Exam/takeExam",
		Method:   "POST",
		Style:    "query",
		Resource: "exam",
		Action:   "take-exam",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_ExamID", Hint: "this.$route.params.id"},
			{Name: "F_Answer", Hint: "a()(t)"},
			{Name: "F_Type", Hint: "1"},
		},
	},
	{
		Path:     "/Fclass/addStudenToClass",
		Method:   "POST",
		Style:    "query",
		Resource: "class",
		Action:   "add-studen-to-class",
		Aliases:  []string{"create"},
		Summary:  "Create",
		Params: []ParamHint{
			{Name: "F_Account", Hint: "\"\""},
		},
	},
	{
		Path:     "/Fclass/addTeacherFromClass",
		Method:   "POST",
		Style:    "query",
		Resource: "class",
		Action:   "add-teacher-from-class",
		Aliases:  nil,
		Summary:  "Create",
		Params: []ParamHint{
			{Name: "teacher", Hint: "this.teacherID"},
			{Name: "F_Classes", Hint: "this.resList.join(\",\")"},
		},
	},
	{
		Path:     "/Fclass/deleteClass",
		Method:   "POST",
		Style:    "query",
		Resource: "class",
		Action:   "delete-class",
		Aliases:  []string{"delete"},
		Summary:  "Delete",
		Params:   nil,
	},
	{
		Path:     "/Fclass/getCanMoveClassList",
		Method:   "POST",
		Style:    "query",
		Resource: "class",
		Action:   "get-can-move-class-list",
		Aliases:  []string{"list"},
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/Fclass/getClassMateRanking",
		Method:   "POST",
		Style:    "query",
		Resource: "class",
		Action:   "get-class-mate-ranking",
		Aliases:  nil,
		Summary:  "Show ranking",
		Params: []ParamHint{
			{Name: "F_ClassID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/Fclass/getClassStudentList",
		Method:   "POST",
		Style:    "query",
		Resource: "class",
		Action:   "get-class-student-list",
		Aliases:  nil,
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/Fclass/getFclassList",
		Method:   "POST",
		Style:    "query",
		Resource: "class",
		Action:   "get-fclass-list",
		Aliases:  nil,
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/Fclass/getMasterClass",
		Method:   "POST",
		Style:    "query",
		Resource: "class",
		Action:   "get-master-class",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_SchoolUserID", Hint: "a"},
		},
	},
	{
		Path:     "/Fclass/getRanking",
		Method:   "POST",
		Style:    "query",
		Resource: "class",
		Action:   "get-ranking",
		Aliases:  nil,
		Summary:  "Show ranking",
		Params: []ParamHint{
			{Name: "F_Type", Hint: "\"0\""},
			{Name: "F_ClassID", Hint: "\"\""},
			{Name: "F_StartTime", Hint: "\"\""},
			{Name: "F_EndTime", Hint: "\"\""},
			{Name: "F_CourseID", Hint: "\"0\""},
			{Name: "F_ChapterID", Hint: "\"0\""},
		},
	},
	{
		Path:     "/Fclass/getStudentClassList",
		Method:   "POST",
		Style:    "query",
		Resource: "class",
		Action:   "get-student-class-list",
		Aliases:  nil,
		Summary:  "List (paginated: data.list + data.count)",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "t.F_ID"},
		},
	},
	{
		Path:     "/Fclass/getTeacherCanMoveClass",
		Method:   "POST",
		Style:    "query",
		Resource: "class",
		Action:   "get-teacher-can-move-class",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "teacher", Hint: "e"},
		},
	},
	{
		Path:     "/Fclass/getTeacherClass",
		Method:   "POST",
		Style:    "query",
		Resource: "class",
		Action:   "get-teacher-class",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params:   nil,
	},
	{
		Path:     "/Fclass/removeClassByTeacher",
		Method:   "POST",
		Style:    "query",
		Resource: "class",
		Action:   "remove-class-by-teacher",
		Aliases:  nil,
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "teacher", Hint: "e"},
			{Name: "F_Class", Hint: "t"},
		},
	},
	{
		Path:     "/Fclass/removeStudentFromClass",
		Method:   "POST",
		Style:    "query",
		Resource: "class",
		Action:   "remove-student-from-class",
		Aliases:  nil,
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "students", Hint: "e.join(\",\")"},
			{Name: "F_Class", Hint: "this.class_id"},
		},
	},
	{
		Path:     "/Fclass/saveFclass",
		Method:   "POST",
		Style:    "query",
		Resource: "class",
		Action:   "save-fclass",
		Aliases:  []string{"save"},
		Summary:  "Save",
		Params: []ParamHint{
			{Name: "F_Status", Hint: "\"1\""},
			{Name: "F_Name", Hint: "\"\""},
			{Name: "F_Memo", Hint: "\"\""},
			{Name: "F_ID", Hint: "\"\""},
			{Name: "F_Grade", Hint: "\"\""},
			{Name: "F_SchoolUserID", Hint: "\"\""},
		},
	},
	{
		Path:     "/Grade/getGradeList",
		Method:   "POST",
		Style:    "query",
		Resource: "grade",
		Action:   "get-grade-list",
		Aliases:  []string{"list"},
		Summary:  "List (paginated: data.list + data.count)",
		Params: []ParamHint{
			{Name: "F_CourseID", Hint: "this.selectedID"},
			{Name: "F_ClassID", Hint: "this.$F_ClassID"},
		},
	},
	{
		Path:     "/Homework/addHomeworkNew",
		Method:   "POST",
		Style:    "query",
		Resource: "homework",
		Action:   "add-homework-new",
		Aliases:  []string{"create"},
		Summary:  "Create",
		Params:   nil,
	},
	{
		Path:     "/Homework/delHomework",
		Method:   "POST",
		Style:    "query",
		Resource: "homework",
		Action:   "del-homework",
		Aliases:  []string{"delete"},
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "e.F_ID"},
		},
	},
	{
		Path:     "/Homework/delPublishScore",
		Method:   "POST",
		Style:    "query",
		Resource: "homework",
		Action:   "del-publish-score",
		Aliases:  nil,
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_HomeworkID", Hint: "i.$route.params.id"},
		},
	},
	{
		Path:     "/Homework/dingzhengHomework",
		Method:   "POST",
		Style:    "body",
		Resource: "homework",
		Action:   "dingzheng-homework",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_SubjectID", Hint: "this.$route.query.sid"},
			{Name: "F_HomeworkID", Hint: "this.$route.query.hid"},
			{Name: "F_CodeContent", Hint: "this.answer"},
			{Name: "F_Language", Hint: "this.language"},
		},
	},
	{
		Path:     "/Homework/doHomework",
		Method:   "POST",
		Style:    "body",
		Resource: "homework",
		Action:   "do-homework",
		Aliases:  []string{"submit"},
		Summary:  "Submit code / answers",
		Params: []ParamHint{
			{Name: "F_SubjectID", Hint: "this.$route.query.sid"},
			{Name: "F_HomeworkID", Hint: "this.$route.query.hid"},
			{Name: "F_CodeContent", Hint: "this.answer"},
			{Name: "F_Language", Hint: "this.language"},
		},
	},
	{
		Path:     "/Homework/endSelfHomework",
		Method:   "POST",
		Style:    "query",
		Resource: "homework",
		Action:   "end-self-homework",
		Aliases:  nil,
		Summary:  "End early",
		Params: []ParamHint{
			{Name: "F_HomeworkID", Hint: "t.$route.params.id"},
		},
	},
	{
		Path:     "/Homework/getHomeworkClass",
		Method:   "POST",
		Style:    "query",
		Resource: "homework",
		Action:   "get-homework-class",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_ClassID", Hint: "this.homework_info.F_ClassID"},
		},
	},
	{
		Path:     "/Homework/getHomeworkList",
		Method:   "POST",
		Style:    "query",
		Resource: "homework",
		Action:   "get-homework-list",
		Aliases:  []string{"list"},
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/Homework/getHomeworkRank",
		Method:   "POST",
		Style:    "query",
		Resource: "homework",
		Action:   "get-homework-rank",
		Aliases:  []string{"rank"},
		Summary:  "Show ranking",
		Params: []ParamHint{
			{Name: "F_ClassID", Hint: "t"},
			{Name: "F_HomeworkID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/Homework/getHomeworkSubject",
		Method:   "POST",
		Style:    "query",
		Resource: "homework",
		Action:   "get-homework-subject",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_HomeworkID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/Homework/getHomeworkTestLog",
		Method:   "POST",
		Style:    "query",
		Resource: "homework",
		Action:   "get-homework-test-log",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_SubjectID", Hint: "this.$route.query.sid"},
			{Name: "F_HomeworkID", Hint: "this.hid"},
		},
	},
	{
		Path:     "/Homework/getSubjectFromHomework",
		Method:   "POST",
		Style:    "query",
		Resource: "homework",
		Action:   "get-subject-from-homework",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/Homework/hideHomework",
		Method:   "POST",
		Style:    "query",
		Resource: "homework",
		Action:   "hide-homework",
		Aliases:  []string{"hide"},
		Summary:  "Hide (soft delete)",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "e.F_ID"},
		},
	},
	{
		Path:     "/Homework/homeworkPartSave",
		Method:   "POST",
		Style:    "upload",
		Resource: "homework",
		Action:   "homework-part-save",
		Aliases:  nil,
		Summary:  "Save",
		Params:   nil,
	},
	{
		Path:     "/Homework/publishScore",
		Method:   "POST",
		Style:    "query",
		Resource: "homework",
		Action:   "publish-score",
		Aliases:  nil,
		Summary:  "Publish results",
		Params: []ParamHint{
			{Name: "F_HomeworkID", Hint: "i.$route.params.id"},
		},
	},
	{
		Path:     "/Homework/subjectDetail",
		Method:   "POST",
		Style:    "query",
		Resource: "homework",
		Action:   "subject-detail",
		Aliases:  []string{"view"},
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_SubjectID", Hint: "this.$route.query.sid"},
			{Name: "F_HomeworkID", Hint: "this.$route.query.hid"},
		},
	},
	{
		Path:     "/Homework/submitHomework",
		Method:   "POST",
		Style:    "query",
		Resource: "homework",
		Action:   "submit-homework",
		Aliases:  nil,
		Summary:  "Submit code / answers",
		Params: []ParamHint{
			{Name: "F_HomeworkID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/Homework/tiQianEnd",
		Method:   "POST",
		Style:    "query",
		Resource: "homework",
		Action:   "ti-qian-end",
		Aliases:  nil,
		Summary:  "End early",
		Params: []ParamHint{
			{Name: "F_HomeworkID", Hint: "t.$route.params.id"},
		},
	},
	{
		Path:     "/Match/addMatchNew",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "add-match-new",
		Aliases:  []string{"create"},
		Summary:  "Create",
		Params:   nil,
	},
	{
		Path:     "/Match/addMatchToClass",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "add-match-to-class",
		Aliases:  nil,
		Summary:  "Create",
		Params: []ParamHint{
			{Name: "F_MatchID", Hint: "this.selectedID"},
			{Name: "F_ClassID", Hint: "this.$F_ClassID"},
		},
	},
	{
		Path:     "/Match/addSubjectToMatch",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "add-subject-to-match",
		Aliases:  nil,
		Summary:  "Create",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "this.selectedID"},
			{Name: "F_Subject", Hint: "this.keys.join(\",\")"},
		},
	},
	{
		Path:     "/Match/canAddList",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "can-add-list",
		Aliases:  nil,
		Summary:  "List available items",
		Params:   nil,
	},
	{
		Path:     "/Match/delMatch",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "del-match",
		Aliases:  []string{"delete"},
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "e.F_ID"},
		},
	},
	{
		Path:     "/Match/delPublishScore",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "del-publish-score",
		Aliases:  nil,
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_MatchID", Hint: "t.F_ID"},
		},
	},
	{
		Path:     "/Match/deleteSubjectFromMatch",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "delete-subject-from-match",
		Aliases:  nil,
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "e.join(\",\")"},
		},
	},
	{
		Path:     "/Match/dingzhengMatch",
		Method:   "POST",
		Style:    "body",
		Resource: "match",
		Action:   "dingzheng-match",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_SubjectID", Hint: "this.$route.query.sid"},
			{Name: "F_MatchID", Hint: "this.$route.query.kid"},
			{Name: "F_CodeContent", Hint: "this.answer"},
			{Name: "F_Language", Hint: "this.language"},
		},
	},
	{
		Path:     "/Match/doMatch",
		Method:   "POST",
		Style:    "body",
		Resource: "match",
		Action:   "do-match",
		Aliases:  []string{"submit"},
		Summary:  "Submit code / answers",
		Params: []ParamHint{
			{Name: "F_SubjectID", Hint: "this.$route.query.sid"},
			{Name: "F_MatchID", Hint: "this.$route.query.kid"},
			{Name: "F_CodeContent", Hint: "this.answer"},
			{Name: "F_Language", Hint: "this.language"},
		},
	},
	{
		Path:     "/Match/endSelfMatch",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "end-self-match",
		Aliases:  nil,
		Summary:  "End early",
		Params: []ParamHint{
			{Name: "F_MatchID", Hint: "t.$route.params.id"},
		},
	},
	{
		Path:     "/Match/exportoffline",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "exportoffline",
		Aliases:  nil,
		Summary:  "Export",
		Params: []ParamHint{
			{Name: "F_MatchID", Hint: "t.$route.params.id"},
			{Name: "F_Problems", Hint: "o()(t.exportConfigProblems)"},
		},
	},
	{
		Path:     "/Match/exportproblemspdf",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "exportproblemspdf",
		Aliases:  nil,
		Summary:  "Export",
		Params: []ParamHint{
			{Name: "F_MatchID", Hint: "t.$route.params.id"},
		},
	},
	{
		Path:     "/Match/exportrecord",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "exportrecord",
		Aliases:  nil,
		Summary:  "Export",
		Params: []ParamHint{
			{Name: "F_MatchID", Hint: "t.$route.params.id"},
		},
	},
	{
		Path:     "/Match/getClassMatch",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "get-class-match",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_ClassID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/Match/getCodeContent",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "get-code-content",
		Aliases:  []string{"code"},
		Summary:  "Show submitted source code",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "t"},
		},
	},
	{
		Path:     "/Match/getCondition",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "get-condition",
		Aliases:  []string{"condition"},
		Summary:  "List filter options",
		Params:   nil,
	},
	{
		Path:     "/Match/getMatchClass",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "get-match-class",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_ClassID", Hint: "this.match_info.F_ClassID"},
		},
	},
	{
		Path:     "/Match/getMatchList",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "get-match-list",
		Aliases:  []string{"list"},
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/Match/getMatchRank",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "get-match-rank",
		Aliases:  []string{"rank"},
		Summary:  "Show ranking",
		Params: []ParamHint{
			{Name: "F_ClassID", Hint: "t"},
			{Name: "F_MatchID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/Match/getMatchStatus",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "get-match-status",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "t.F_ID"},
		},
	},
	{
		Path:     "/Match/getMatchSubject",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "get-match-subject",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_MatchID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/Match/getMatchTestLog",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "get-match-test-log",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_SubjectID", Hint: "this.$route.query.sid"},
			{Name: "F_MatchID", Hint: "this.kid"},
		},
	},
	{
		Path:     "/Match/getStudentMatch",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "get-student-match",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params:   nil,
	},
	{
		Path:     "/Match/getSubjectFromMatch",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "get-subject-from-match",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "this.$route.query.MatchID"},
		},
	},
	{
		Path:     "/Match/hideMatch",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "hide-match",
		Aliases:  []string{"hide"},
		Summary:  "Hide (soft delete)",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "e.F_ID"},
		},
	},
	{
		Path:     "/Match/importoffline",
		Method:   "POST",
		Style:    "upload",
		Resource: "match",
		Action:   "importoffline",
		Aliases:  nil,
		Summary:  "Import",
		Params:   nil,
	},
	{
		Path:     "/Match/matchPartSave",
		Method:   "POST",
		Style:    "upload",
		Resource: "match",
		Action:   "match-part-save",
		Aliases:  []string{"save"},
		Summary:  "Save",
		Params:   nil,
	},
	{
		Path:     "/Match/publishScore",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "publish-score",
		Aliases:  nil,
		Summary:  "Publish results",
		Params: []ParamHint{
			{Name: "F_MatchID", Hint: "t.F_ID"},
		},
	},
	{
		Path:     "/Match/showBagExplain",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "show-bag-explain",
		Aliases:  nil,
		Summary:  "Toggle a switch",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "t.F_ID"},
			{Name: "F_IsShowBagExplain", Hint: "i"},
		},
	},
	{
		Path:     "/Match/studentGetMatchSubject",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "student-get-match-subject",
		Aliases:  nil,
		Summary:  "Fetch (student view)",
		Params: []ParamHint{
			{Name: "F_MatchID", Hint: "this.$route.query.aid"},
			{Name: "F_ClassID", Hint: "this.$route.query.cid"},
		},
	},
	{
		Path:     "/Match/subjectDetail",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "subject-detail",
		Aliases:  []string{"view"},
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_SubjectID", Hint: "this.$route.query.sid"},
			{Name: "F_MatchID", Hint: "this.$route.query.kid"},
		},
	},
	{
		Path:     "/Match/submitMatch",
		Method:   "POST",
		Style:    "body",
		Resource: "match",
		Action:   "submit-match",
		Aliases:  nil,
		Summary:  "Submit code / answers",
		Params: []ParamHint{
			{Name: "F_MatchID", Hint: "this.$route.params.id"},
			{Name: "F_ClassID", Hint: "this.$route.query.cid"},
		},
	},
	{
		Path:     "/Match/tiQianEnd",
		Method:   "POST",
		Style:    "query",
		Resource: "match",
		Action:   "ti-qian-end",
		Aliases:  nil,
		Summary:  "End early",
		Params: []ParamHint{
			{Name: "F_MatchID", Hint: "t.F_ID"},
		},
	},
	{
		Path:     "/Origin/deleteOrigin",
		Method:   "POST",
		Style:    "query",
		Resource: "origin",
		Action:   "delete-origin",
		Aliases:  []string{"delete"},
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "t.F_ID"},
		},
	},
	{
		Path:     "/Origin/getOriginList",
		Method:   "POST",
		Style:    "query",
		Resource: "origin",
		Action:   "get-origin-list",
		Aliases:  []string{"list"},
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/Origin/saveOrigin",
		Method:   "POST",
		Style:    "query",
		Resource: "origin",
		Action:   "save-origin",
		Aliases:  []string{"save"},
		Summary:  "Save",
		Params: []ParamHint{
			{Name: "F_Name", Hint: "\"\""},
			{Name: "F_Sort", Hint: "\"\""},
			{Name: "F_ID", Hint: "\"\""},
		},
	},
	{
		Path:     "/Subject/changeStatus",
		Method:   "POST",
		Style:    "query",
		Resource: "subject",
		Action:   "change-status",
		Aliases:  nil,
		Summary:  "Update",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "this.subjectInfo.F_ID"},
			{Name: "F_Status", Hint: "e"},
		},
	},
	{
		Path:     "/Subject/deleteDistributionFile",
		Method:   "POST",
		Style:    "body",
		Resource: "subject",
		Action:   "delete-distribution-file",
		Aliases:  []string{"delete"},
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_Problem", Hint: "e"},
			{Name: "filenames", Hint: "a.join(\",\")"},
		},
	},
	{
		Path:     "/Subject/deleteTestdataFile",
		Method:   "POST",
		Style:    "body",
		Resource: "subject",
		Action:   "delete-testdata-file",
		Aliases:  nil,
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_Problem", Hint: "e"},
			{Name: "filenames", Hint: "o.join(\",\")"},
		},
	},
	{
		Path:     "/Subject/getCondition",
		Method:   "POST",
		Style:    "query",
		Resource: "subject",
		Action:   "get-condition",
		Aliases:  []string{"condition"},
		Summary:  "List filter options",
		Params:   nil,
	},
	{
		Path:     "/Subject/getConfigYaml",
		Method:   "POST",
		Style:    "body",
		Resource: "subject",
		Action:   "get-config-yaml",
		Aliases:  nil,
		Summary:  "Show system config",
		Params: []ParamHint{
			{Name: "F_Problem", Hint: "e"},
		},
	},
	{
		Path:     "/Subject/getDistributionFiles",
		Method:   "POST",
		Style:    "body",
		Resource: "subject",
		Action:   "get-distribution-files",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "t.sizeForm.F_ID"},
		},
	},
	{
		Path:     "/Subject/getSubject",
		Method:   "POST",
		Style:    "query",
		Resource: "subject",
		Action:   "get-subject",
		Aliases:  []string{"view"},
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "this.$route.query.sid"},
			{Name: "F_ChapterID", Hint: "this.$route.query.zid || \"\""},
			{Name: "F_CourseID", Hint: "this.$route.query.cid || \"\""},
			{Name: "F_MatchID", Hint: "this.$route.query.kid || \"\""},
			{Name: "F_HomeworkID", Hint: "this.$route.query.hid || \"\""},
		},
	},
	{
		Path:     "/Subject/getSubjectForManager",
		Method:   "POST",
		Style:    "query",
		Resource: "subject",
		Action:   "get-subject-for-manager",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/Subject/getSubjectList",
		Method:   "POST",
		Style:    "query",
		Resource: "subject",
		Action:   "get-subject-list",
		Aliases:  []string{"list"},
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/Subject/getSubjectListNew",
		Method:   "POST",
		Style:    "query",
		Resource: "subject",
		Action:   "get-subject-list-new",
		Aliases:  nil,
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/Subject/nextPid",
		Method:   "POST",
		Style:    "body",
		Resource: "subject",
		Action:   "next-pid",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params:   nil,
	},
	{
		Path:     "/Subject/subjectSave",
		Method:   "POST",
		Style:    "body",
		Resource: "subject",
		Action:   "subject-save",
		Aliases:  []string{"save"},
		Summary:  "Save",
		Params: []ParamHint{
			{Name: "id", Hint: "t.id"},
			{Name: "score", Hint: "Number(t.score)"},
			{Name: "type", Hint: "t.type"},
		},
	},
	{
		Path:     "/Tag/deleteTag",
		Method:   "POST",
		Style:    "query",
		Resource: "tag",
		Action:   "delete-tag",
		Aliases:  []string{"delete"},
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "t.F_ID"},
		},
	},
	{
		Path:     "/Tag/getTagList",
		Method:   "POST",
		Style:    "query",
		Resource: "tag",
		Action:   "get-tag-list",
		Aliases:  []string{"list"},
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/Tag/saveTag",
		Method:   "POST",
		Style:    "query",
		Resource: "tag",
		Action:   "save-tag",
		Aliases:  []string{"save"},
		Summary:  "Save",
		Params: []ParamHint{
			{Name: "F_Name", Hint: "\"\""},
			{Name: "F_Status", Hint: "\"1\""},
			{Name: "F_Order", Hint: "\"\""},
			{Name: "F_ID", Hint: "\"\""},
			{Name: "F_ParentID", Hint: "0"},
		},
	},
	{
		Path:     "/Tag/showTagList",
		Method:   "POST",
		Style:    "query",
		Resource: "tag",
		Action:   "show-tag-list",
		Aliases:  nil,
		Summary:  "Toggle a switch",
		Params:   nil,
	},
	{
		Path:     "/TestLog/TestLogDetail",
		Method:   "POST",
		Style:    "query",
		Resource: "testlog",
		Action:   "test-log-detail",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/TestLog/TestPoint",
		Method:   "POST",
		Style:    "query",
		Resource: "testlog",
		Action:   "test-point",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "this.$route.params.id"},
		},
	},
	{
		Path:     "/TestLog/doTest",
		Method:   "POST",
		Style:    "body",
		Resource: "testlog",
		Action:   "do-test",
		Aliases:  []string{"submit"},
		Summary:  "Submit code / answers",
		Params: []ParamHint{
			{Name: "F_SubjectID", Hint: "this.$route.query.sid"},
			{Name: "F_CourseID", Hint: "this.$route.query.cid"},
			{Name: "F_Chapter", Hint: "this.$route.query.zid"},
			{Name: "F_MatchID", Hint: "this.kid"},
			{Name: "F_CodeContent", Hint: "this.answer"},
			{Name: "F_Language", Hint: "this.language"},
		},
	},
	{
		Path:     "/TestLog/getCodeContent",
		Method:   "POST",
		Style:    "query",
		Resource: "testlog",
		Action:   "get-code-content",
		Aliases:  []string{"code"},
		Summary:  "Show submitted source code",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "e"},
		},
	},
	{
		Path:     "/TestLog/getSubjectTestLog",
		Method:   "POST",
		Style:    "query",
		Resource: "testlog",
		Action:   "get-subject-test-log",
		Aliases:  nil,
		Summary:  "Fetch data",
		Params: []ParamHint{
			{Name: "F_SubjectID", Hint: "this.$route.query.sid"},
		},
	},
	{
		Path:     "/TestLog/getTestLogList",
		Method:   "POST",
		Style:    "query",
		Resource: "testlog",
		Action:   "get-test-log-list",
		Aliases:  []string{"list"},
		Summary:  "List (paginated: data.list + data.count)",
		Params: []ParamHint{
			{Name: "F_ChapterID", Hint: "this.chapterID"},
			{Name: "F_CourseID", Hint: "this.F_CourseID"},
			{Name: "F_MatchID", Hint: "this.F_MatchID"},
			{Name: "F_HomeworkID", Hint: "this.F_HomeworkID"},
			{Name: "F_UserAccount", Hint: "\"\""},
			{Name: "F_UserName", Hint: "this.user_name"},
			{Name: "F_Language", Hint: "\"\""},
			{Name: "F_ClassID", Hint: "\"\""},
			{Name: "F_StartTime", Hint: "\"\""},
			{Name: "F_EndTime", Hint: "\"\""},
			{Name: "F_Res", Hint: "\"\""},
			{Name: "F_Problem", Hint: "this.F_Problem"},
			{Name: "page", Hint: "1"},
			{Name: "F_UserID", Hint: "\"\""},
		},
	},
	{
		Path:     "/TestLog/submitNoJudge",
		Method:   "POST",
		Style:    "query",
		Resource: "testlog",
		Action:   "submit-no-judge",
		Aliases:  nil,
		Summary:  "Submit code / answers",
		Params:   nil,
	},
	{
		Path:     "/User/accountPreview",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "account-preview",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_Names", Hint: "e"},
			{Name: "F_Pre", Hint: "this.account_pre"},
		},
	},
	{
		Path:     "/User/bindPhone",
		Method:   "GET",
		Style:    "query",
		Resource: "user",
		Action:   "bind-phone",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_Phone", Hint: "\"\""},
			{Name: "F_Code", Hint: "\"\""},
			{Name: "F_Account", Hint: "this.account"},
		},
	},
	{
		Path:     "/User/changePasswordByPhone",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "change-password-by-phone",
		Aliases:  nil,
		Summary:  "Update",
		Params: []ParamHint{
			{Name: "new_pwd", Hint: "e.ruleFormSmsPwd.new_pwd"},
			{Name: "new_pwd2", Hint: "e.ruleFormSmsPwd.new_pwd2"},
			{Name: "F_Code", Hint: "e.ruleFormSmsPwd.F_Code"},
		},
	},
	{
		Path:     "/User/checkTeacher",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "check-teacher",
		Aliases:  nil,
		Summary:  "Review",
		Params: []ParamHint{
			{Name: "F_Status", Hint: "e"},
			{Name: "F_ID", Hint: "t"},
		},
	},
	{
		Path:     "/User/deleteUser",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "delete-user",
		Aliases:  []string{"delete"},
		Summary:  "Delete",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "e.join(\",\")"},
		},
	},
	{
		Path:     "/User/editAccount",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "edit-account",
		Aliases:  []string{"update"},
		Summary:  "Update",
		Params: []ParamHint{
			{Name: "account", Hint: "\"\""},
		},
	},
	{
		Path:     "/User/editPwd",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "edit-pwd",
		Aliases:  nil,
		Summary:  "Update",
		Params: []ParamHint{
			{Name: "user_pwd", Hint: "\"\""},
			{Name: "user_name", Hint: "\"\""},
			{Name: "F_Phone", Hint: "\"\""},
			{Name: "F_Code", Hint: "\"\""},
			{Name: "skip_bind_phone", Hint: "\"\""},
		},
	},
	{
		Path:     "/User/getConfig",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "get-config",
		Aliases:  []string{"config"},
		Summary:  "Show system config",
		Params:   nil,
	},
	{
		Path:     "/User/getMasterList",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "get-master-list",
		Aliases:  []string{"list"},
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/User/getNotCheckTeacherList",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "get-not-check-teacher-list",
		Aliases:  nil,
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/User/getStudentListNew",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "get-student-list-new",
		Aliases:  nil,
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/User/getUserList",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "get-user-list",
		Aliases:  nil,
		Summary:  "List (paginated: data.list + data.count)",
		Params:   nil,
	},
	{
		Path:     "/User/heartbeat",
		Method:   "GET",
		Style:    "query",
		Resource: "user",
		Action:   "heartbeat",
		Aliases:  nil,
		Summary:  "Heartbeat ping",
		Params:   nil,
	},
	{
		Path:     "/User/inviteStudent",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "invite-student",
		Aliases:  nil,
		Summary:  "Invite",
		Params: []ParamHint{
			{Name: "F_Accounts", Hint: "e.join(\",\")"},
			{Name: "F_Ctype", Hint: "this.inviteStatusRadio"},
			{Name: "F_ClassID", Hint: "this.inviteClassID"},
		},
	},
	{
		Path:     "/User/login",
		Method:   "GET",
		Style:    "query",
		Resource: "user",
		Action:   "login",
		Aliases:  nil,
		Summary:  "Log in",
		Params: []ParamHint{
			{Name: "user_pwd", Hint: "\"\""},
			{Name: "user_name", Hint: "\"\""},
			{Name: "F_Phone", Hint: "\"\""},
			{Name: "F_Code", Hint: "\"\""},
			{Name: "skip_bind_phone", Hint: "\"\""},
		},
	},
	{
		Path:     "/User/loginByPhone",
		Method:   "GET",
		Style:    "query",
		Resource: "user",
		Action:   "login-by-phone",
		Aliases:  nil,
		Summary:  "Log in",
		Params: []ParamHint{
			{Name: "user_pwd", Hint: "\"\""},
			{Name: "user_name", Hint: "\"\""},
			{Name: "F_Phone", Hint: "\"\""},
			{Name: "F_Code", Hint: "\"\""},
			{Name: "skip_bind_phone", Hint: "\"\""},
		},
	},
	{
		Path:     "/User/oneKeyResetPwd",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "one-key-reset-pwd",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_ID", Hint: "s.join(\",\")"},
		},
	},
	{
		Path:     "/User/operationInvite",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "operation-invite",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "F_Status", Hint: "e"},
			{Name: "F_ID", Hint: "t.inviteList[t.inviteIndex].F_ID"},
		},
	},
	{
		Path:     "/User/register",
		Method:   "GET",
		Style:    "query",
		Resource: "user",
		Action:   "register",
		Aliases:  nil,
		Summary:  "Register",
		Params: []ParamHint{
			{Name: "F_Password", Hint: "\"\""},
			{Name: "F_Name", Hint: "\"\""},
			{Name: "F_Type", Hint: "\"4\""},
			{Name: "F_Phone", Hint: "\"\""},
			{Name: "F_Code", Hint: "\"\""},
			{Name: "F_SchoolName", Hint: "\"\""},
			{Name: "F_Period", Hint: "\"\""},
		},
	},
	{
		Path:     "/User/resetPasswordByPhone",
		Method:   "GET",
		Style:    "query",
		Resource: "user",
		Action:   "reset-password-by-phone",
		Aliases:  nil,
		Summary:  "Reset / change password",
		Params: []ParamHint{
			{Name: "user_pwd", Hint: "\"\""},
			{Name: "F_Phone", Hint: "\"\""},
			{Name: "F_Code", Hint: "\"\""},
			{Name: "user_pwd_again", Hint: "\"\""},
		},
	},
	{
		Path:     "/User/resetPwd",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "reset-pwd",
		Aliases:  nil,
		Summary:  "Reset / change password",
		Params: []ParamHint{
			{Name: "F_UserID", Hint: "t.F_ID"},
		},
	},
	{
		Path:     "/User/searchInvite",
		Method:   "GET",
		Style:    "query",
		Resource: "user",
		Action:   "search-invite",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params:   nil,
	},
	{
		Path:     "/User/sendCodeForBind",
		Method:   "GET",
		Style:    "query",
		Resource: "user",
		Action:   "send-code-for-bind",
		Aliases:  nil,
		Summary:  "Send SMS code",
		Params: []ParamHint{
			{Name: "phone", Hint: "this.ruleFormBindPhone.F_Phone"},
			{Name: "F_Account", Hint: "this.ruleFormBindPhone.F_Account"},
		},
	},
	{
		Path:     "/User/sendCodeForChangePwd",
		Method:   "GET",
		Style:    "query",
		Resource: "user",
		Action:   "send-code-for-change-pwd",
		Aliases:  nil,
		Summary:  "Send SMS code",
		Params:   nil,
	},
	{
		Path:     "/User/sendCodeForCheck",
		Method:   "GET",
		Style:    "query",
		Resource: "user",
		Action:   "send-code-for-check",
		Aliases:  nil,
		Summary:  "Send SMS code",
		Params: []ParamHint{
			{Name: "phone", Hint: "this.ruleFormCheckPhone.F_Phone"},
		},
	},
	{
		Path:     "/User/sendCodeForLogin",
		Method:   "GET",
		Style:    "query",
		Resource: "user",
		Action:   "send-code-for-login",
		Aliases:  nil,
		Summary:  "Send SMS code",
		Params: []ParamHint{
			{Name: "phone", Hint: "this.ruleForm2.F_Phone"},
		},
	},
	{
		Path:     "/User/sendCodeForRegister",
		Method:   "GET",
		Style:    "query",
		Resource: "user",
		Action:   "send-code-for-register",
		Aliases:  nil,
		Summary:  "Send SMS code",
		Params: []ParamHint{
			{Name: "phone", Hint: "this.ruleForm2.F_Phone"},
		},
	},
	{
		Path:     "/User/sendCodeForResetPassword",
		Method:   "GET",
		Style:    "query",
		Resource: "user",
		Action:   "send-code-for-reset-password",
		Aliases:  nil,
		Summary:  "Send SMS code",
		Params: []ParamHint{
			{Name: "phone", Hint: "this.ruleForm2.F_Phone"},
		},
	},
	{
		Path:     "/User/studentCreate",
		Method:   "POST",
		Style:    "upload",
		Resource: "user",
		Action:   "student-create",
		Aliases:  nil,
		Summary:  "Create",
		Params: []ParamHint{
			{Name: "F_Name", Hint: "\"\""},
			{Name: "F_Class", Hint: "\"0\""},
			{Name: "F_Type", Hint: "\"4\""},
			{Name: "F_Status", Hint: "\"1\""},
		},
	},
	{
		Path:     "/User/studentSort",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "student-sort",
		Aliases:  nil,
		Summary:  "Fetch (student view)",
		Params:   nil,
	},
	{
		Path:     "/User/studentUpdate",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "student-update",
		Aliases:  nil,
		Summary:  "Update",
		Params: []ParamHint{
			{Name: "F_Names", Hint: "\"\""},
			{Name: "F_Name", Hint: "\"\""},
			{Name: "F_Status", Hint: "\"\""},
			{Name: "F_ID", Hint: "\"\""},
		},
	},
	{
		Path:     "/User/userCreate",
		Method:   "POST",
		Style:    "query",
		Resource: "user",
		Action:   "user-create",
		Aliases:  nil,
		Summary:  "Create",
		Params: []ParamHint{
			{Name: "F_Status", Hint: "\"1\""},
			{Name: "F_Name", Hint: "\"\""},
			{Name: "F_Type", Hint: "\"3\""},
			{Name: "F_Sex", Hint: "\"1\""},
			{Name: "F_Master", Hint: "this.$userinfo(\"F_ID\")"},
			{Name: "F_ID", Hint: "\"\""},
			{Name: "F_Class", Hint: "\"\""},
		},
	},
	{
		Path:     "/subject/batchsyncfromhydro",
		Method:   "GET",
		Style:    "query",
		Resource: "hydro",
		Action:   "batchsyncfromhydro",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "status", Hint: "this.importEnabled ? 1 : 0"},
		},
	},
	{
		Path:     "/subject/tongbufromhydrooj",
		Method:   "GET",
		Style:    "query",
		Resource: "hydro",
		Action:   "tongbufromhydrooj",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params: []ParamHint{
			{Name: "problemID", Hint: "n[o]"},
			{Name: "status", Hint: "e.importEnabled ? 1 : 0"},
		},
	},
	{
		Path:     "/user/adminIndex",
		Method:   "POST",
		Style:    "query",
		Resource: "home",
		Action:   "admin-index",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params:   nil,
	},
	{
		Path:     "/user/schoolMasterIndex",
		Method:   "POST",
		Style:    "query",
		Resource: "home",
		Action:   "school-master-index",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params:   nil,
	},
	{
		Path:     "/user/studentIndex",
		Method:   "POST",
		Style:    "query",
		Resource: "home",
		Action:   "student-index",
		Aliases:  nil,
		Summary:  "Fetch (student view)",
		Params: []ParamHint{
			{Name: "F_UserID", Hint: "this.$route.query.id"},
		},
	},
	{
		Path:     "/user/teacherIndex",
		Method:   "POST",
		Style:    "query",
		Resource: "home",
		Action:   "teacher-index",
		Aliases:  nil,
		Summary:  "Perform operation",
		Params:   nil,
	},
}

// Resource 描述一个资源分组
type Resource struct {
	Name    string
	Aliases []string
	Summary string
}

var Resources = []Resource{
	{Name: "bag", Aliases: []string{"paper-bag"}, Summary: "Paper bags: bundle and reuse problems"},
	{Name: "chapter", Aliases: nil, Summary: "Chapters: course chapters, exams and rankings"},
	{Name: "chapter-subject", Aliases: []string{"cs"}, Summary: "Chapter problems: link problems to chapters"},
	{Name: "course", Aliases: nil, Summary: "Courses: CRUD, students and rankings"},
	{Name: "difficulty", Aliases: []string{"diff"}, Summary: "Difficulty labels"},
	{Name: "exam", Aliases: nil, Summary: "Exams: papers, problems and exam logs"},
	{Name: "class", Aliases: []string{"fclass"}, Summary: "Classes: CRUD and member links"},
	{Name: "grade", Aliases: nil, Summary: "Grades"},
	{Name: "homework", Aliases: []string{"hw"}, Summary: "Homework: publish, answer, grade, scores"},
	{Name: "match", Aliases: nil, Summary: "Matches: create, answer, ranking, export"},
	{Name: "origin", Aliases: nil, Summary: "Problem sources"},
	{Name: "subject", Aliases: []string{"problem"}, Summary: "Problems: CRUD, test data, Hydro sync"},
	{Name: "tag", Aliases: nil, Summary: "Problem tags"},
	{Name: "testlog", Aliases: []string{"log"}, Summary: "Judge logs: submit, results, view code"},
	{Name: "user", Aliases: nil, Summary: "Users: login, register, password, accounts"},
	{Name: "home", Aliases: []string{"index"}, Summary: "Home dashboards (four roles)"},
	{Name: "hydro", Aliases: nil, Summary: "Hydro OJ problem sync"},
}

var endpointByPath = func() map[string]*Endpoint {
	m := make(map[string]*Endpoint, len(Endpoints))
	for i := range Endpoints {
		m[Endpoints[i].Path] = &Endpoints[i]
	}
	return m
}()

// Lookup 按资源名 + 动作名（或别名）查找端点
func Lookup(resource, action string) *Endpoint {
	var fallback *Endpoint
	for i := range Endpoints {
		ep := &Endpoints[i]
		if !matchResource(resource, ep) {
			continue
		}
		if ep.Action == action {
			return ep
		}
		for _, a := range ep.Aliases {
			if a == action {
				return ep
			}
		}
		if fallback == nil {
			fallback = ep
		}
	}
	return fallback
}

func matchResource(name string, ep *Endpoint) bool {
	if ep.Resource == name {
		return true
	}
	for _, r := range Resources {
		if r.Name == ep.Resource {
			for _, a := range r.Aliases {
				if a == name {
					return true
				}
			}
		}
	}
	return false
}

// ByPath 按完整路径查找
func ByPath(path string) *Endpoint {
	return endpointByPath[path]
}
